version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: payload-postgres
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: W4r!p9eT7zQ2@fLm8H
      POSTGRES_DB: payload_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
